resources:
  - ../../base
  - missing-file.yaml

namespace: prod

configMapGenerator:
  - name: demo-config
    behavior: replace
    envs:
      - configmap.env

patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
