apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - analysis-template.yaml

configMapGenerator:
  - name: demo-config
    envs:
      - configmap.env

generatorOptions:
  disableNameSuffixHash: true
